### ISSUE TITLE
Access token in display

### ISSUE THREAD

**Issue by morales-felix** [zanderman12/blog_post_code#1]
Hey Alex,

This is Felix, we were on a BYOD group last May, and was volunteered for a study of yours regarding gait.

I remembered about your blog, and recommended it to a current BYOD member given his interest in scraping Twitter data. In taking a look at one of your functions, we saw you had access tokens in display for some of your code.

Not sure if you're aware of this, but thought it would be good to give you a heads up.

**Comment by zanderman12** [comment]
Hey Felix, Thanks for letting me know. Probably best to keep those hidden, just updated the repo to remove them. Hope you are doing well.
